// Login action types
export const LOG_IN_REQUEST = 'LOG_IN_REQUEST'
export const LOG_IN_SUCCESS = 'LOG_IN_SUCCESS'
export const LOG_IN_FAILURE = 'LOG_IN_FAILURE'

// Profile action types
export const PROFILE_EDIT = 'PROFILE_EDIT'
export const PROFILE_FIELD_CHANGE = 'PROFILE_FIELD_CHANGE'
export const PROFILE_CANCEL_EDITING = 'PROFILE_CANCEL_EDITING'
export const PROFILE_SAVE_REQUEST = 'PROFILE_SAVE_REQUEST'
export const PROFILE_SAVE_SUCCESS = 'PROFILE_SAVE_SUCCESS'
